---
# tasks file for mysql_db
    -
      name: Install the mysql rpm from remote repo 
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present
    -
      name: Upgrade all package
      yum:
        name: '*'
        state: latest 
    -
      name: Install mysql 
      yum: 
        name: mysql-server
        state: latest
    - 
      name: Start mysql and enable
      service:  
        name: mysql
        state: started
        enabled: yes
    -
      name: Create new database with name 'employee_db'
      mysql_db:
        name: '{{ db_name }}'
        state: present
    -
      name: Create database user with name 'db_user' and all database privilege
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: '*.*:ALL'
        state: present
      no_log: true

    - 
      name:  Insert data to database
      command: mysql -e "USE {{ db_name }};CREATE TABLE employees (name VARCHAR(20));INSERT INTO employees VALUES ('JOHN');"
      ignore_errors: True